version: '3'

services:
  orders-db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - '${PORT_DB:-5432}:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data